### ISSUE TITLE
Requirements Definition

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#1]
Please comment whatever you determine from the requirements definition...

**Comment by yash101** [comment]
# What codecs are better for streaming vs. storage?
## Performance measured by:
- Compression ratio
- Resources necessary

- Mostly FOX uses 720p, but is trying to move to 1080p, 59.94Hz (60Hz)
    - Also try UHD / 4K
    - HDR / 10 bit color depth / etc.
 
- Start at 720p and go up to 4K / whatever
    - Use 720p as the baseline
- Check out multiple-pass encoding

**Comment by yash101** [comment]
# Comparisons:
- Appropriate for Streaming:
  - Bitrate & Compression
  - Motion & Blockiness
  - VMAF qualitative evaluation?
  - Colorspace issues: bit depth of color space compression
- Playout Evaluation
  - Generational losses

## Article on compression artifacts:
[Compression Artifacts](https://blog.biamp.com/understanding-video-compression-artifacts)

**Comment by himeganfoy** [comment]
This is the technical delivery file format for Broadcast playout and represents the mezzanine golden files we would use. 

[14_january2016_TechnicalSpecs.pdf](https://github.com/CSE-485-Capstone/Main-Repo/files/3796188/14_january2016_TechnicalSpecs.pdf)

[Commercial_J2019_Technical_Delivery.pdf](https://github.com/CSE-485-Capstone/Main-Repo/files/3796189/Commercial_J2019_Technical_Delivery.pdf)

**Comment by yash101** [comment]
[VMAF (suggested by Ben)](https://github.com/Netflix/vmaf)
