### ISSUE TITLE
Week 1: Identify everyone's skills, interests figure out how to split work.

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#14]
We need to all meet and respond with our skills and interests

**Comment by yash101** [comment]
Deliverable: figure out what problem we want to solve.

**Comment by sid-rawal** [comment]
My main skills that would be relevant to this project are writing scripts in Bash or Python to run automated tests. I could work on tests in FFmpeg and/or putting together results and analyses. I do not have experience with OpenCV but I could learn more about it and work with it if need be.

**Comment by aaronpgurrola** [comment]
I enjoyed using OpenCV for the small bit of code I did. Wouldn't mind working on the opencv required code.

**Comment by himeganfoy** [comment]
Create analytics API, or actual algorithms

**Comment by himeganfoy** [comment]
GOAL: Identify and consider different codecs for different profiles. e.g. streaming video for sports

**Comment by himeganfoy** [comment]
Codecs for Sports: H264 and H265

Create adversarial scenarios, e.g. noise

Requirements/Test these features against separate levels/profiles: 
1. Compression - bit rate
2. Noise - popcorn noise, crowd noise 
3. Blocking
4. Blur - subject measurement, e.g. camera pans

**Comment by himeganfoy** [comment]
Need to complete: 

1. Frame by frame analysis - create algorithms and build API to run tests and record results (C++, Python) @yash101 
2. Quantify the metrics - output vectors [all team effort] 
3. Rank importance or specify the calculation/performance [all team effort] 
4. Researching industry benchmarks @aaronpgurrola 
5. Make recommendations, codecs is best for [blank] but not [blank] [all team effort]

**Comment by yash101** [comment]
Building the initial API that you all can use to build your tests upon.

**Comment by himeganfoy** [comment]
NEXT FRIDAY: 
1. Platform for testing, build tests

**Comment by yash101** [comment]
@himeganfoy Friday, 2/13 is during spring break. We are currently planning week 2 to be the week of Friday, 2/20.

**Comment by yash101** [comment]
Closing this issue because the week has ended and it looks like we all have an idea of our deliverables this semester.
