### ISSUE TITLE
[REPLY REQUESTED] Weekly Meeting?

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#16]
Should we have a weekly meeting to work on things together?

**Comment by yash101** [comment]
Friday 2:00 PM works?

**Comment by smuruga5** [comment]
Works for me

**Comment by sid-rawal** [comment]
I have weekly lab meetings from 2:00-4:00 so if we can do 1pm that would work best. Otherwise after 4 works too.

**Comment by yash101** [comment]
How does 4p work for everyone? I'm available all day Fridays with prior
notice.

Thank You,
Devyash Lodha
Website <https://devyashis.me/> | LinkedIn
<https://www.linkedin.com/in/yash101>
Arizona State University

**Comment by smuruga5** [comment]
4pm works for me.

**Comment by benbricken** [comment]
4pm works for me too

**Comment by aaronpgurrola** [comment]
Fridays I work 3pm-8pm

**Comment by yash101** [comment]
So currently, Friday after 4pm works with everyone except Aaron. Should we all meet without Aaron? Fridays are the only day with practical availability for me.

**Comment by yash101** [comment]
Meeting on 3/16/2020 is from 12 noon to 12:30 PM currently. We can discuss final meeting times during this meeting. Goal: determine what we have to implement and figure out who wants to do what.

**Comment by yash101** [comment]
Finalizing for every week at 4p till whenever every week.
Week of 3/7/2020-3/15/2020 will have no meetings or work.
