### ISSUE TITLE
[PROJECT MANAGEMENT] Scrum standups

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#18]
We should all post daily a single sentence with what we are doing today on Slack.

**Comment by yash101** [comment]
@aaronpgurrola @benbricken @aaronpgurrola @smuruga5 @sid-rawal should we create a gh issue daily and comment what we are doing on there instead?

Also I think because this isn't a full-time job, we should post every other day.

**Comment by aaronpgurrola** [comment]
I agree. I think we should post maybe Twice a week? Monday and Friday? Almost like "Here's what we're doing this week" and "here's what I did this week"

**Comment by yash101** [comment]
pRoJeCt Is CoMpLeTe!
