### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#2]
- Different codecs
- What are we researching? Basically identifying the definition
- Learning phase
- Tools at our disposal

## Tools at our disposal:
- FFMPEG (libavcodec, ffmpeg CLI, etc.)
- OpenCV
- HEVC reference models
- Files (TODO)

## Tests
- Check definition for tests

**Comment by himeganfoy** [comment]
Links from Jason at AWS: 

https://blog.biamp.com/understanding-video-compression-artifacts/

General:
 
https://arxiv.org/pdf/1903.00473.pdf

https://www.embedded.com/video-compression-artifacts-and-mpeg-noise-reduction/

https://developer.nvidia.com/ffmpeg

https://aws.amazon.com/marketplace/pp/Code-Creator-FFMPEG-Media-Converter-HVM/B07516C1CN#pdp-pricing

https://aws.amazon.com/ec2/pricing/on-demand/

https://aws.amazon.com/ec2/spot/

https://aws.amazon.com/mediaconvert/

**Comment by yash101** [comment]
Closing this issue because we are done with our research phase.
