### ISSUE TITLE
Meeting - 3/27/2020

### ISSUE THREAD

**Issue by yash101** [CSE-485-Capstone/Main-Repo#20]
- Get data from NASA - videos of launches, etc.
- Start with a completely uncompressed video, which would test perfectly - max bitrate possible
  - Compress this video to determine how each of the codecs perform
  - Compress until we start seeing artefacts or responses in our metrics

**Comment by yash101** [comment]
Find deadlines for when to complete things by?

**Comment by himeganfoy** [comment]
Adding another video codec comparison paper here: https://arxiv.org/abs/2003.10282

**Comment by himeganfoy** [comment]
Friday April 3 – conduct tests on compression via VMAF/MPEG-Dash, present your findings to Alfonso, this is not a planning meeting
Friday April 10 – conduct tests on bit rate via VMAF/MPEG-Dash, present your findings to Alfonso, this is not a planning meeting
Friday April 17 – compile compression and bit rate findings into a presentation, gather feedback, this is not a planning meeting
FINAL TEAM MEETING Friday April 25 – share your presentation with Winston and Dan
