### ISSUE TITLE
Get access to test files

### ISSUE THREAD

**Issue by benbricken** [CSE-485-Capstone/Main-Repo#3]
Golden Files/Mezzanine Files that can be used to test codecs.

Well known files (Big Buck Bunny, etc) are preferred as standard baselines, and should be at least 4k HDR to test high quality targets.

## (EDIT): Adding links to the file provider services below:
- [Big Buck Bunny renders](http://bbb3d.renderfarming.net/download.html)
- [Fox Media Box](https://app.box.com/s/i4lcwqp9ttdln9px8cdslkmtduna4kez)

**Comment by benbricken** [comment]
Big Buck Bunny can be found at this link:
http://bbb3d.renderfarming.net/download.html

It was decided that until we find a way to use a true uncompressed mezzanine, the native resolution in the .mp4 format will be the standard test file

**Comment by himeganfoy** [comment]
FOX CONTENT: to be emailed

Box link to Excel file: https://app.box.com/s/i4lcwqp9ttdln9px8cdslkmtduna4kez

**Comment by yash101** [comment]
Just note that this bug tracker is public so if this is a private link, it should be emailed.

**Comment by yash101** [comment]
Closing this issue because it has been resolved. Links to the requested are above. The initial issue will be updated to contain the links.

**Comment by yash101** [comment]
Updated link with files requested.

**Comment by himeganfoy** [comment]
@yash101 Link has been updated and will be available for 90 days.
